### ISSUE TITLE
Give death to the user with whom he was in combat

### ISSUE THREAD

**Issue by SeDark** [SirBlobman/CombatLogX#33]
I am using this plugin together with KitBattle Advanced, and I would like that when the user disconnects the death give to the user with whom he was hitting.

**Comment by SirBlobman** [comment]
Why would you kill the person who did not log out of combat?

**Comment by SeDark** [comment]
When a user disconnects and dies, death is not taken by anyone, it simply dies.

What I want is that death can add to the counter of the player with whom he was fighting.

**Comment by Segysmundo** [comment]
@SirBlobman 

What he's saying is that **[KitBattle Advanced](https://www.spigotmc.org/resources/kitbattle-advanced.2872/)** has a reward system that grants experience, coins and stats when you kill players. So when someone attempts to dc in combat, **CombatLogX** kills him and the player that was about to kill the dc'er gets no reward since it's the "server taking the kill".

So it would be great if when someone disconnects in combat, **CombatLogX** would give the kill to the last guy that hit him.
