### ISSUE TITLE
Message Color incorrect

### ISSUE THREAD

**Issue by WongIong** [SirBlobman/CombatLogX#492]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

![image](https://user-images.githubusercontent.com/36799194/185214764-9b14e5d1-cdfd-4a22-a831-54f1e5930337.png)
Color Code is not workinig

### Reproduction Steps

1. start the server

### Expected behaviour

Message should be colored

### CombatLogX Version

![image](https://user-images.githubusercontent.com/36799194/185215268-ccd34f6b-956d-4d54-8a11-3cbf90825db0.png)

**Comment by Olivoz** [comment]
BlueSlimeCore (and CombatLogX) now use Adventure MiniMessage instead of legacy chat colors. To convert your old language file you can use this tool: https://github.com/SirBlobman/YAML-Legacy-to-MiniMessage/

You can read about more Adventure MiniMessage here: https://docs.adventure.kyori.net/minimessage/format.html
