### ISSUE TITLE
Force Fields and NPCs

### ISSUE THREAD

**Issue by uhjiogdsffkjhgds** [SirBlobman/CombatLogX#8]
Hey,
Thanks for adding the last feature request, I have another one that might interest you.
So there is a plugin called CombatTagPlus (https://www.spigotmc.org/resources/combattagplus.4775/)
In that plugin there is a feature where it Spawn's a forcefield and it doesn't let you get back to the safe zone. I know that your plugin has something similar where you get slightly teleported backwards but I think it would be cool to add a forcefield to help keep the player immersed and stop him from getting teleported.

Thank you for your time.

**Comment by SirBlobman** [comment]
Could you show me a video of the force field in action? Maybe I can try to replicate it

**Comment by FreeKillGR** [comment]
Will do but when I get home because I currently have limited internet access

**Comment by FreeKillGR** [comment]
Also, another cool feature that the plugin mentioned above has is npc's. When the player disconnects an npc spawns in his location and the other player has to kill the npc to get the items if the player logs back and the npc is not dead then the npc disappears and the reconnected player gets the npcs health and items

So for example 

If I have 5  hearts left and I leave the server 
an npc will spawn that will have 5 hearts 
if it gets killed it drops all the items and when i log back in i'm dead 
if the npc gets damaged (2 hearts) but i log back in before it dies i will have my items and everything but i will now have 3 hearts (because the npc took 2 hearts damage)

If the npc does not get killed in 1 minute it will get killed automatically and drop the player items
That one should be a bit more challenging to make but it's a really cool feature that also helps with immersion.

Thank you for your time.

**Comment by hasanas83V2001** [comment]
The ncp is a good idea, but the forcefield would cause a lot of unneccesary lag, please don't replace it

**Comment by FreeKillGR** [comment]
I never said replace i said add a new feature that can be enabled and disabled so someone with more powerful servers (like mine) could have a really cool feature.

P.S it's not really that heavy at all (at least in the old plugin) I was running it on a cheap shared server and had no lag what so ever.

**Comment by hasanas83V2001** [comment]
Yeah if you could enable/disable it, it would be a really nice addon.

**Comment by SirBlobman** [comment]
Added NPCs in 5.0.0+

**Comment by SirBlobman** [comment]
Added force fields in 7.0.0.3+
