### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by zikehalil3535** [SirBlobman/CombatLogX#856]
### Server Implementation

Spigot

### Server Version

1.19.4

### Describe the bug

Im getting error while Im trying to fight

### Reproduction Steps

1. Starting the battle
2. Getting Error like this

### Expected behaviour

I dont know why Im getting that.

### latest log file (if applicable)

https://paste.gg/p/anonymous/0378b1c297744270ba2f9417c5f3e139/files/4b752a29e4a84da09cc7d252e3dd357e/raw

### CombatLogX Version

11.5.0.0.1242
Current Purpur Version: 1.21.1-2311-0fa9a50 (MC: 1.21.1)*

**Comment by Olivoz** [comment]
This has already been fixed in beta builds. If you do not want to update disable the [inventory closing](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) feature of the Cheat Prevention expansion.

Related to #837, #839, #847, #851 and #855
